CREATE ROLE covid
LOGIN
SUPERUSER;
CREATE SCHEMA covid AUTHORIZATION covid
CREATE TABLE CASES (
    ID INT NOT NULL,
    CONTINENT VARCHAR(50),
    COUNTRY VARCHAR(50),
    TOTAL_CASES NUMERIC,
    PRIMARY KEY(ID)
);
commit;