INSERT INTO COVID.CASES (id,continent, country,TOTAL_CASES) VALUES (1,'Asia','Afghanistan',2568456);
INSERT INTO COVID.CASES (id,continent, country,TOTAL_CASES) VALUES (2,'North America','United States',84375459);
INSERT INTO COVID.CASES (id,continent, country,TOTAL_CASES) VALUES (3,'Asia','India',43125370);
INSERT INTO COVID.CASES (id,continent, country,TOTAL_CASES) VALUES (4,'South America','Brazil',30701900);
INSERT INTO COVID.CASES (id,continent, country,TOTAL_CASES) VALUES (5,'Europe','France',29233309);
INSERT INTO COVID.CASES (id,continent, country,TOTAL_CASES) VALUES (6,'Europe','Germany',25892255);
INSERT INTO COVID.CASES (id,continent, country,TOTAL_CASES) VALUES (7,'Europe','United Kingdom',22207102);
INSERT INTO COVID.CASES (id,continent, country,TOTAL_CASES) VALUES (8,'Europe','Russia',18268958);
INSERT INTO COVID.CASES (id,continent, country,TOTAL_CASES) VALUES (9,'Europe','Italy',17116550);
INSERT INTO COVID.CASES (id,continent, country,TOTAL_CASES) VALUES (10,'Europe','Turkey',15055576);
INSERT INTO COVID.CASES (id,continent, country,TOTAL_CASES) VALUES (11,'Europe','Turkey',15055576);
INSERT INTO COVID.CASES (id,continent, country,TOTAL_CASES) VALUES (12,'Asia','South Korea',17830429);
INSERT INTO COVID.CASES (id,continent, country,TOTAL_CASES) VALUES (13,'Asia','North Korea',163658414);