CREATE USER covid IDENTIFIED BY covid;

GRANT CREATE SESSION, ALTER SESSION, CREATE DATABASE LINK,
CREATE MATERIALIZED VIEW, CREATE PROCEDURE, CREATE PUBLIC SYNONYM,
CREATE ROLE, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE,
CREATE TRIGGER, CREATE TYPE, CREATE VIEW, UNLIMITED TABLESPACE
    TO covid;

CREATE TABLE COVID.CASES (
    ID NUMBER NOT NULL,
    CONTINENT VARCHAR2(50 BYTE),
    COUNTRY VARCHAR2(50 BYTE),
    TOTAL_CASES NUMBER,
    PRIMARY KEY(id)
);

CREATE SEQUENCE COVID.cases_seq;

CREATE TABLE COVID.CONTINENT (
     ID NUMBER NOT NULL,
     CONTINENT VARCHAR2(50 BYTE),
     COUNTRY VARCHAR2(50 BYTE),
     TOTAL_CASES NUMBER,
     PRIMARY KEY(id)
);



commit;